public class Constants {
    // Account
    public static String ACCOUNT_RECORD_TYPE_1 = 'Account_Record_Type'; // Business
    public static String ACCOUNT_RECORD_TYPE_2 = 'Channel_Partner_Account';
    public static String ACCOUNT_RECORD_TYPE_3 = 'Consumer_Account_Record_Type';
    public static String ACCOUNT_RECORD_TYPE_4 = 'Supplier';
    // Contact
    public static String CONTACT_RECORD_TYPE_1 = 'Business';
    public static String CONTACT_RECORD_TYPE_2 = 'Channel';
    // Interaction
    public static String INTERACTION_LOCATION_TYPE_1 = 'Commercial';
    public static String INTERACTION_LOCATION_TYPE_2 = 'Residential';
    // Lead
    public static String LEAD_RECORD_TYPE_1 = 'Lead_Record_Type'; // Business
    public static String LEAD_RECORD_TYPE_2 = 'Channel_Lead';
    public static String LEAD_RECORD_TYPE_3 = 'Consumer';
    // Location
    public static String LOCATION_RECORD_TYPE_1  = 'Area';
    public static String LOCATION_RECORD_TYPE_2  = 'Property';
    public static String LOCATION_TYPE_1         = 'Sales Region';
    public static String LOCATION_TYPE_2         = 'Market Area';
    public static String LOCATION_TYPE_3         = 'Commercial';
    public static String LOCATION_TYPE_4         = 'Residential';
    public static String LOCATION_DEFAULT_REGION = 'National Openreach';
    // Task
    public static String TASK_RECORD_TYPE_1       = 'ADP_Review';
    public static String TASK_RECORD_TYPE_LABEL_1 = 'ADP Review';
    public static String TASK_STATUS_1            = 'Not Started';
    // Utilities
    public static String UTILITIES_DATE_FREQUENCY_1 = 'Monthly';
    public static String UTILITIES_DATE_FREQUENCY_2 = 'Quarterly';
    public static String UTILITIES_DATE_FREQUENCY_3 = 'Yearly';
    public static String UTILITIES_DATE_PERIOD_1    = '1 Month';
    public static String UTILITIES_DATE_PERIOD_2    = '3 Months';
    public static String UTILITIES_DATE_PERIOD_3    = '6 Months';
    public static String UTILITIES_DATE_PERIOD_4    = '12 Months';
    public static String UTILITIES_STATUS_1         = 'Active';
}